# Generated by Django 5.1.6 on 2025-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_chasek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karzina_tovar',
            name='kolichestvo',
            field=models.IntegerField(default=1),
        ),
    ]
